// A j-time plugin: one CommonJS module exporting one object.
//
// This file runs inside the app's main process, so it has Node and Electron —
// `require('fs')`, `require('electron').clipboard`, fetch, child_process, all of
// it. What it hands back is plain data: rows for the palette, and commands the
// rows can name. Nothing here draws anything; the app does that.
//
// Edit this file, then run "Reload plugins" in the palette to see the change.
// See AGENTS.md next to this folder for the whole contract.

const { clipboard } = require('electron');

/** "Name https://url" per line, in any order, blank lines ignored. */
function parse(text) {
  return String(text || '')
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => {
      const at = line.lastIndexOf(' ');
      return at === -1
        ? { name: line, url: line }
        : { name: line.slice(0, at).trim(), url: line.slice(at + 1) };
    })
    .filter((link) => /^https?:\/\//.test(link.url));
}

module.exports = {
  // What the section is called. The folder name is the id.
  title: 'Bookmarks',

  // How often to call refresh() while the app runs, in milliseconds. 0 means
  // only when the palette opens or something changed.
  refreshMs: 0,

  // The settings form, generated by the app. `secret: true` on a field makes it
  // a password box that is encrypted on disk and never shown again.
  fields: [
    {
      key: 'links',
      label: 'Links',
      type: 'textarea',
      placeholder: 'GitHub https://github.com',
      note: 'One per line: a name, a space, and the URL.',
    },
  ],

  // Config for a fresh install.
  defaults: () => ({
    links: ['j-time https://github.com/rustybucket-cloud/j-time', 'Atlassian https://id.atlassian.com'].join('\n'),
  }),

  // False shows the section as "Not set up" and never calls refresh().
  configured: (config) => parse(config.links).length > 0,

  // What's on screen. Called with the current config; return rows.
  async refresh(config) {
    const rows = parse(config.links).map((link) => ({
      id: link.url,
      title: link.name,
      subtitle: link.url,
      keywords: [new URL(link.url).hostname],
      lead: 'dot',
      // Enter opens the link. A row can instead name a command: { command: 'x', args: [...] }.
      run: { url: link.url },
      // ⌘K on the row. `shortcut` makes ⌘L run it while the row is selected —
      // avoid letters the app menu owns (H, Q, W, C, V, X, A).
      actions: [
        { id: 'copy', title: 'Copy link', run: { command: 'copy', args: [link.url], stay: true }, shortcut: 'l' },
      ],
    }));
    return {
      rows,
      // Section-level commands, opened with ⌘K on the header.
      actions: [{ id: 'first', title: 'Open the first one', run: { url: rows[0]?.id || 'https://github.com' } }],
    };
  },

  // What rows can name. Return a string for a toast, { ok: false, error } to
  // complain, or nothing. `host.refresh()` re-runs refresh() afterwards.
  commands: {
    copy: ([url]) => {
      clipboard.writeText(String(url));
      return 'Copied';
    },
  },

  // What this plugin puts on j-time's MCP endpoint, for Claude Code and any
  // other MCP client to call. Named `bookmarks_*` there, so two plugins can both
  // have a `search`. Arguments are named — the caller can't see the screen —
  // and the answer is text, because text is all it gets.
  tools: [
    {
      name: 'search',
      description: 'Search the saved bookmarks by name or host. Returns matching names and URLs.',
      // JSON Schema for each argument. The app wraps these in the object schema.
      input: { q: { type: 'string', description: 'Part of a name or hostname.' } },
      required: ['q'],
      // readOnly lets a client skip asking permission; destructive makes it ask.
      readOnly: true,
      run: ({ q }, host, config) => {
        const needle = String(q || '').toLowerCase();
        const hits = parse(config.links).filter((link) =>
          `${link.name} ${link.url}`.toLowerCase().includes(needle),
        );
        if (hits.length === 0) return `No bookmark matches "${q}".`;
        return hits.map((link) => `${link.name} — ${link.url}`).join('\n');
      },
    },
  ],
};
